packages:
  - "apps/*"
  - "packages/*"

catalog:
  "typescript": "5.8.3"

  "zod": "3.24.2"

  "eslint": "9.24.0"
  "@antfu/eslint-config": "4.11.0"

  "payload": 3.33.0
  "@payloadcms/live-preview": 3.33.0
  "@payloadcms/db-postgres": 3.33.0
  "@payloadcms/next": 3.33.0
  "@payloadcms/payload-cloud": 3.33.0
  "@payloadcms/plugin-nested-docs": 3.33.0
  "@payloadcms/plugin-seo": 3.33.0
  "@payloadcms/richtext-lexical": 3.33.0
  "@payloadcms/ui": 3.33.0
