packages:
  - "apps/*"
  - "packages/*"

catalog:
  "typescript": "5.8.3"

  "zod": "3.24.3"

  "eslint": "9.24.0"
  "@antfu/eslint-config": "4.12.0"

  "payload": 3.35.1
  "@payloadcms/live-preview": 3.35.1
  "@payloadcms/db-postgres": 3.35.1
  "@payloadcms/next": 3.35.1
  "@payloadcms/payload-cloud": 3.35.1
  "@payloadcms/plugin-nested-docs": 3.35.1
  "@payloadcms/plugin-seo": 3.35.1
  "@payloadcms/richtext-lexical": 3.35.1
  "@payloadcms/ui": 3.35.1

  "@orpc/client": "1.0.3"
  "@orpc/server": "1.0.3"