packages:
  - apps/*
  - packages/*
catalog:
  typescript: 5.8.3
  zod: 3.25.23
  eslint: 9.27.0
  '@antfu/eslint-config': 4.13.2
  payload: 3.39.1
  '@payloadcms/live-preview': 3.39.1
  '@payloadcms/db-postgres': 3.39.1
  '@payloadcms/next': 3.39.1
  '@payloadcms/payload-cloud': 3.39.1
  '@payloadcms/plugin-nested-docs': 3.39.1
  '@payloadcms/plugin-seo': 3.39.1
  '@payloadcms/richtext-lexical': 3.39.1
  '@payloadcms/ui': 3.39.1
  '@orpc/client': 1.3.0
  '@orpc/server': 1.3.0
onlyBuiltDependencies:
  - '@tailwindcss/oxide'
  - esbuild
  - unrs-resolver
  - vue-demi
